import jsPDF from "jspdf";
import "jspdf-autotable";
import * as XLSX from "xlsx";

// Export table data to Excel
export function exportToExcel(data: Record<string, string | number>[], headers: { key: string; label: string }[], filename: string) {
  const wsData = [
    headers.map(h => h.label),
    ...data.map(row => headers.map(h => row[h.key] ?? ""))
  ];
  const ws = XLSX.utils.aoa_to_sheet(wsData);
  // Set RTL
  ws["!cols"] = headers.map(() => ({ wch: 20 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
  XLSX.writeFile(wb, `${filename}.xlsx`);
}

// Export invoice to PDF
export function exportInvoicePDF(invoice: {
  invoiceNumber: string;
  title: string;
  issueDate: string;
  dueDate: string;
  clientName: string;
  companyName: string;
  items: { description: string; quantity: number; unitPrice: number; total: number }[];
  subtotal: number;
  taxRate: number;
  taxAmount: number;
  totalAmount: number;
  status: string;
}) {
  const doc = new jsPDF();

  // Header background
  doc.setFillColor(27, 42, 74); // #1C1B2E
  doc.rect(0, 0, 210, 45, "F");

  // Company name (use default font for Arabic compatibility - simple approach)
  doc.setTextColor(201, 168, 76); // #C9A84C
  doc.setFontSize(24);
  doc.text("MARSA", 105, 20, { align: "center" });

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text("Invoice / \u0641\u0627\u062a\u0648\u0631\u0629", 105, 32, { align: "center" });

  // Invoice details
  doc.setTextColor(27, 42, 74);
  doc.setFontSize(10);
  let y = 55;

  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 15, y);
  doc.text(`Date: ${new Date(invoice.issueDate).toLocaleDateString("en-US")}`, 15, y + 7);
  doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString("en-US")}`, 15, y + 14);
  doc.text(`Status: ${invoice.status}`, 15, y + 21);

  doc.text(`Client: ${invoice.clientName}`, 120, y);
  doc.text(`Company: ${invoice.companyName}`, 120, y + 7);

  // Items table
  (doc as any).autoTable({
    startY: y + 35,
    head: [["#", "Description", "Qty", "Unit Price", "Total"]],
    body: invoice.items.map((item, i) => [
      i + 1,
      item.description,
      item.quantity,
      item.unitPrice.toLocaleString("en-US") + " SAR",
      item.total.toLocaleString("en-US") + " SAR",
    ]),
    headStyles: { fillColor: [27, 42, 74], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 246, 240] },
    styles: { halign: "center", fontSize: 9 },
    columnStyles: { 1: { halign: "left" } },
  });

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(10);
  doc.text(`Subtotal: ${invoice.subtotal.toLocaleString("en-US")} SAR`, 140, finalY);
  doc.text(`Tax (${invoice.taxRate}%): ${invoice.taxAmount.toLocaleString("en-US")} SAR`, 140, finalY + 7);
  doc.setFontSize(12);
  doc.setFont(undefined as any, "bold");
  doc.text(`Total: ${invoice.totalAmount.toLocaleString("en-US")} SAR`, 140, finalY + 16);

  // Footer
  doc.setFontSize(8);
  doc.setFont(undefined as any, "normal");
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by MARSA System", 105, 285, { align: "center" });

  doc.save(`invoice-${invoice.invoiceNumber}.pdf`);
}
